source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'


target 'DynamicInvoker_Tests', :exclusive => true do
  pod "DynamicInvoker", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
